language: node_js
node_js: '8'
install:
  - npm install
  - cd client/ && npm install
before_script:
  - cd client/ && npm run build
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  skip_cleanup: true
  on: master
